<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ResizingClient.Tests</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.6.2" />
    <PackageReference Include="MSTest.TestFramework" Version="3.6.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ResizingClient\ResizingClient.csproj" />
  </ItemGroup>
</Project>